# -*- coding: utf-8 -*-
"""setup..ynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-MyMeaDPDlKLBHIk2buaIE-rUTjqHQL0
"""

import os
os.system('color a')
setting = int(input("Apakah library Numpy, IPython, Matplotlib, Scipy, dan pprint sudah anda install? 1: Sudah, 2: Belum >>>"))
if setting == 1:
  os.system('pip install numpy')
  os.system('pip install ipython')
  os.system('pip install matplotlib')
  os.system('pip install scipy')
  os.system('pip install pprintpp')
else:
  print("Oke kita bisa memulai program^^")
os.system('python code/codemetnum11.py')
k=input("Tekan ENTER untuk exit")